config/routes.rb
Rails.application.routes.draw do
  # Googleログイン
  post '/google_login_api/callback', to: 'google_login_api#callback'
  
  root 'menus#index'

  resources :users do
    member do
      get :favorites
    end
  end

  resources :menus do
    member do
      post :favorite, to: 'favorites#create'
    end

    resource :favorite, only: [:destroy]

    collection do
      get :back, action: :back
      post :confirm_new, action: :confirm_new
    end
    get :search, on: :collection
  end

  namespace :mypage do
    resources :tree, only: [:index]
  end

  resources :sessions, only: [:new, :create, :destroy]

  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy', as: :logout_get

  # フッターのリンクを作成
  get 'privacy', to: 'pages#privacy', as: :privacy
  get 'terms', to: 'pages#terms', as: :terms

  # お問い合わせメール
  namespace :public do
    resources :contacts, only: [:new, :create] do
      collection do
        post 'confirm'
        post 'back'
        get 'done'
      end
    end
  end
end

app/models/menu.rb
class Menu < ApplicationRecord
  mount_uploader :menu_image, MenuImageUploader
  
  belongs_to :user

  validates :name, presence: { message: 'メニュー名を入力してください' }
  validates :menu_image, presence: { message: "メニュー画像を選択してください" }
  validates :material, presence: { message: '材料を入力してください' }
  validates :quantity, presence: { message: '分量を入力してください' }
  validates :make, presence: { message: '作り方を入力してください' }
  validates :point, presence: { message: 'ポイントを入力してください' }
  validates :genre, presence: { message: 'ジャンルを選択してください' }
  validates :hot, presence: { message: '辛さレベルを選択してください' }

  # お気に入り機能
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy 

  def favorited_by(user)
    Favorite.find_by(user_id: user.id, menu_id: id)
  end

  # 検索機能
  def self.search(query)
    ransack(name_or_material_cont: query).result
  end

  validate :make_present
  validate :material_present
  validate :quantity_present
  
  private

  def make_present
    if make.blank? || make.all?(&:blank?)
      errors.add(:make, '作り方を入力してください')
    end
  end

  def material_present
    if material.blank? || material.all?(&:blank?)
      errors.add(:material, '材料を入力してください')
    end
  end

  def quantity_present
    if quantity.blank? || quantity.all?(&:blank?)
      errors.add(:quantity, '分量を入力してください')
    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: %i[ show edit update destroy ]
  skip_before_action :require_login, only: %i[index show]

  def index
    @menus = Menu.all
    @q = Menu.ransack(params[:q])
    @menus = @q.result(distinct: true).includes(:user).page(params[:page]).order("created_at desc")
  end

  def show
    @q = Menu.ransack(params[:q])
  end

  def new
    @menu = Menu.new
    @q = Menu.ransack(params[:q])
    @menu.material = [''] if @menu.material.blank? # 空の要素を1つ追加して初期化
    @menu.quantity = [''] if @menu.quantity.blank? # 空の要素を1つ追加して初期化
    @menu.make = [''] if @menu.make.blank? # 空の要素を1つ追加して初期化
  end

  def edit
    @menu = Menu.find(params[:id])
    @q = Menu.ransack(params[:q])
  end

  def create
    @q = Menu.ransack(params[:q])
    @menu = current_user.menus.new(menu_params)

    if params[:back]
      render :new
    elsif @menu.save
      redirect_to @menu, success: '投稿しました'
    else
      render :new
    end
  end

  def update
    @q = Menu.ransack(params[:q])
    if @menu.update(menu_params)
      redirect_to menu_url(@menu), success: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    menu = Menu.find(params[:id])
    menu.destroy
    redirect_to menus_url, success: '削除しました'
  end

  def favorites
    @favorites_menus = current_user.favorite_menus.includes(:user).order(created_at: :desc)
  end

  def confirm_new
    @q = Menu.ransack(params[:q])
    @menu = current_user.menus.new(menu_params)
  
    if !@menu.menu_image.present?
      @menu.menu_image.retrieve_from_cache!(session[:menu_image_cache])
    end
  
    if @menu.valid?
      session[:menu] = @menu.attributes
      session[:menu_image_cache] = @menu.menu_image.cache_name
      render :confirm_new
    else
      render :new
    end
  end
  

  def back
    @q = Menu.ransack(params[:q])
    @menu = Menu.new(session[:menu]) if session[:menu]
    render :new
  end

  def search
    @menus = Menu.where("name like ?", "%#{params[:q]}%")
    respond_to do |format|
      format.js
    end
  end

  private
    def set_menu
      @menu = Menu.find(params[:id])
    end

    def menu_params
      params.require(:menu).permit(:name, :genre, :hot, :point, :menu_image, :menu_image_cache, material: [], quantity: [], make: [])
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_favorite.html.erb
<%= link_to favorite_menu_path(menu), method: :post do %>
  <i class="bi bi-star"></i>
<% end %>

app/views/menus/_favorite_button.html.erb
<% if current_user && current_user.favorite?(menu) %>
  <%= render 'menus/unfavorite', { menu: menu } %>
<% else %>
  <%= render 'menus/favorite', { menu: menu } %>
<% end %>

app/views/menus/_form.html.erb
<%= javascript_include_tag 'menus' %>

<%= form_with(model: @menu, url: confirm_new_menus_path, local: true) do |f| %>
  <div class="mb-3">
    <%= f.label :name, "メニュー名" %>
    <%= f.text_field :name, class: 'form-control' %>
    <% if @menu.errors[:name].any? %>
      <div class="text-danger"><%= @menu.errors[:name].first %></div>
    <% end %>
  </div>

  <div class="form-row d-flex">
    <div class="flex-grow-1">
      <div class="menu-image-prev" onclick="document.getElementById('menu_image_field').click();">
        <% if @menu.menu_image.present? %>
          <%= image_tag @menu.menu_image.thumb.url, alt: "menu-image", id: "img_prev", class: "img-thumbnail", size: "300x105" %>
        <% else %>
          <%= image_tag "menu-default-image.png", alt: "menu-image", id: :img_prev, class: "img-thumbnail", size: "300x105" %>
        <% end %>
        <%= f.file_field :menu_image, id: "menu_image_field", class: "hidden", accept: "image/*", onchange: "previewImage(this);", style: "display:none;" %>
      </div>
      <% if @menu.errors[:menu_image].any? %>
          <div class="text-danger"><%= @menu.errors[:menu_image].first %></div>
      <% end %>
    </div>

    <div class="flex-grow-1">
      <div class="card-body">
        <div id="material_quantity_form_area">
          <!-- 材料と分量のフィールド -->
          <% @menu.material.each_with_index do |material, index| %>
            <div class="form-group">
              <input type="text" name="menu[material][]" id="a<%= index %>" value="<%= material %>" placeholder="材料　(例)玉ねぎ">
              <input type="text" name="menu[quantity][]" id="b<%= index %>" value="<%= @menu.quantity[index] %>" placeholder="分量　(例)200g">
              <button type="button" id="<%= index %>" onclick="deleteForms(this.id)">削除</button>
            </div>
          <% end %>
        </div>
        <% if @menu.errors[:material].any? %>
          <div class="text-danger"><%= @menu.errors[:material].first %></div>
        <% end %>
        <% if @menu.errors[:quantity].any? %>
          <div class="text-danger"><%= @menu.errors[:quantity].first %></div>
        <% end %>
        <button type="button" class="btn btn-secondary mt-2" onclick="addMaterialQuantityForms()">材料と分量を追加</button>
      </div>
    </div>
  </div>

  <div class="form-row d-flex mt-3">
    <div class="flex-grow-1">
      <div class="mb-3">
        <%= f.label :genre, "カレーのジャンル" %>
        <%= f.select :genre, [["バターチキンカレー", "バターチキンカレー"], ["ドライカレー", "ドライカレー"], ["グリーンカレー", "グリーンカレー"], ["スープカレー", "スープカレー"], ["ビーフカレー", "ビーフカレー"], ["ポークカレー", "ポークカレー"], ["カツカレー", "カツカレー"], ["シーフードカレー", "シーフードカレー"], ["野菜カレー", "野菜カレー"], ["その他", "その他"]], include_blank: "選択して下さい", selected: @menu.genre %>
        <% if @menu.errors[:genre].any? %>
            <div class="text-danger"><%= @menu.errors[:genre].first %></div>
        <% end %>
      </div>
    </div>
    <div class="flex-grow-1">
      <div class="mb-3">
        <%= f.label :hot, "辛さレベル" %>
        <%= f.select :hot, [["1:甘口", "1:甘口"], ["2:甘口〜中辛", "2:甘口〜中辛"], ["3:中辛", "3:中辛"], ["4:中辛〜辛口", "4:中辛〜辛口"], ["5:辛口", "5:辛口"]], include_blank: "選択して下さい", selected: @menu.hot %>
        <% if @menu.errors[:hot].any? %>
            <div class="text-danger"><%= @menu.errors[:hot].first %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="mb-3 mx-3">
    作り方
    <div id="make_form_area">
      <!-- 作り方ステップのフィールド -->
      <% @menu.make.each_with_index do |make, index| %>
        <div class="form-group">
          <label for="make_step_<%= index + 1 %>">ステップ<%= index + 1 %></label>
          <textarea name="menu[make][]" id="make_step_<%= index + 1 %>" class="form-control" rows="8" placeholder="作り方のステップ"><%= make %></textarea>
          <button type="button" id="<%= index + 1 %>" onclick="deleteMakeStep(this.id)">削除</button>
        </div>
      <% end %>
    </div>
    <% if @menu.errors[:make].any? %>
      <div class="text-danger"><%= @menu.errors[:make].first %></div>
    <% end %>
    <button type="button" class="btn btn-secondary mt-2" onclick="addMakeStep()">作り方を追加</button>
  </div>

  <div class="mb-3 mx-3">
    <%= f.label :point, "ポイント" %>
    <%= f.text_area :point, placeholder: "こだわったポイントなどを記入", class: 'form-control', rows: 8 %>
    <% if @menu.errors[:point].any? %>
      <div class="text-danger"><%= @menu.errors[:point].first %></div>
    <% end %>
  </div>

  <%= f.submit '確認画面へ', class: 'btn btn-primary' %>
<% end %>

app/views/menus/_menu.html.erb
<div class="col">
  <div class="card p-3 h-100">
    <%= link_to menu_path(menu), class: 'menu-card', style: 'text-decoration: none; color: inherit;' do %>
      <h4 class="card-title fw-bold">
        <%= menu.name %>
      </h4>

      <div class="menu-content-container">
        <div class="menu-image">
          <% if menu.menu_image.present? %>
            <%= image_tag menu.menu_image.url, alt: 'Menu Image', class: 'img-menu_image', style: 'max-width: 100%;' %>
          <% else %>
            画像なし
          <% end %>
        </div>
      </div>
    <% end %>
    <hr />
      <div class="card-body">
        <div class="d-flex align-items-center justify-content-between">
          <div class="d-flex align-items-center gap-3">
            <% if menu.user.present? %>
              <p class="card-text"><%= menu.user.name %></p>
            <% else %>
              <p class="card-text">Unknown User</p>
            <% end %>
          </div>

          <% if current_user && current_user.own?(menu) %>
            <%= render 'menus/favorite_button', menu: menu %>
          <% else %>
            <%= render 'menus/favorite_button', menu: menu %>
          <% end %>

        </div>
      </div>
  </div>
</div>

app/views/menus/_unfavorite.html.erb
<%= link_to menu_favorite_path(menu),method: :delete do %>
  <i class="bi bi-star-fill"></i>
<% end %>

app/views/menus/confirm_new.html.erb
<%= form_with model: @menu, url: menus_path, local: true do |f| %>
  <div class="container">
    <div class="row">
      <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1 class="text-center mb-4 mt-4">メニュー確認</h1>
        <div class="card mt-3">
          <div class="card-body">
            <div class="card-body">
              <h1>
                <%= @menu.name %>
              </h1>
              <div class="row">
                <div class="col-md-6">
                  <%= image_tag @menu.menu_image.url, class: 'w-100 mb-3' %>
                </div>

                <!-- 材料と分量のリストを表示 -->
                <div class="col-md-4">
                  <div class="card mb-3">
                    <div class="card-header">
                      材料と分量
                    </div>
                    <ul class="list-group list-group-flush">
                      <% @menu.material.each_with_index do |material, index| %>
                        <li class="list-group-item d-flex justify-content-between">
                          <span><%= material %></span>
                          <span><%= @menu.quantity[index] %></span>
                        </li>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>

              <div class="card mb-3">
                <div class="card-header">
                  作り方
                </div>
                <div class="card-body">
                  <% @menu.make.each_with_index do |step, index| %>
                    <div class="card mb-3">
                      <div class="card-header">
                        ステップ<%= index + 1 %>
                      </div>
                      <div class="card-body">
                        <p><%= Rinku.auto_link(simple_format(step), :all, 'target="_blank"').html_safe %></p>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>

              <div class="card mb-3">
                <div class="card-header">
                  ポイント
                </div>
                <div class="card-body">
                  <%= @menu.point %>
                </div>
              </div>

              <div class="card mb-3">
                <div class="card-header">
                  カレーのジャンル
                </div>
                <div class="card-body">
                  <%= @menu.genre %>
                </div>
              </div>

              <div class="card mb-3">
                <div class="card-header">
                  辛さレベル
                </div>
                <div class="card-body">
                  <%= @menu.hot %>
                </div>
              </div>

              <%= form_for :menu, url: back_menus_path, method: :get do |f| %>
                <% if current_user&.own?(@menu) %>
                  <%= f.hidden_field :name %>
                  <%= f.hidden_field :material, multiple: true, value: @menu.material %>
                  <%= f.hidden_field :quantity, multiple: true, value: @menu.quantity %>
                  <%= f.hidden_field :make, multiple: true, value: @menu.make %>
                  <%= f.hidden_field :point %>
                  <%= f.hidden_field :menu_image_cache %>
                  <%= f.hidden_field :genre %>
                  <%= f.hidden_field :hot %>
                  <%= f.submit '戻る', name: 'back', class: 'btn btn-primary ml-2' %>
                <% end %>
              <% end %>
              <%= f.submit '公開する', class: 'btn btn-primary ml-2' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/menus/edit.html.erb
<%= javascript_include_tag 'menus' %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
    <h1 class="text-center mb-4 mt-4">編集</h1>
      <div class="card mt-3">
        <div class="card-body">
          <%= form_with(model: @menu, url: menu_path(@menu), method: :patch) do |f| %>
            <div class="mb-3">
              <%= f.label :name, "メニュー名" %>
              <%= f.text_field :name, class: 'form-control' %>
              <% if @menu.errors[:name].any? %>
                <div class="text-danger"><%= @menu.errors[:name].first %></div>
              <% end %>
            </div>

            <div class="form-row d-flex">
              <div class="flex-grow-1">
                <div class="menu-image-prev" onclick="document.getElementById('menu_image_field').click();">
                  <% if @menu.menu_image.present? %>
                    <%= image_tag @menu.menu_image.thumb.url, alt: "menu-image", id: "img_prev", class: "img-thumbnail", size: "300x105" %>
                  <% else %>
                    <%= image_tag "menu-default-image.png", alt: "menu-image", id: :img_prev, class: "img-thumbnail", size: "300x105" %>
                  <% end %>
                  <%= f.file_field :menu_image, id: "menu_image_field", class: "hidden", accept: "image/*", onchange: "previewImage(this);", style: "display:none;" %>
                </div>
                <% if @menu.errors[:menu_image].any? %>
                    <div class="text-danger"><%= @menu.errors[:menu_image].first %></div>
                <% end %>
              </div>

              <div class="flex-grow-1">
                <div class="card-body">
                  <div id="material_quantity_form_area">
                    <!-- 材料と分量のフィールド -->
                    <% @menu.material.each_with_index do |material, index| %>
                      <div class="form-group">
                        <input type="text" name="menu[material][]" id="a<%= index %>" value="<%= material %>" placeholder="材料">
                        <input type="text" name="menu[quantity][]" id="b<%= index %>" value="<%= @menu.quantity[index] %>" placeholder="分量">
                        <button type="button" id="<%= index %>" onclick="deleteForms(this.id)">削除</button>
                      </div>
                    <% end %>
                  </div>
                  <% if @menu.errors[:material].any? %>
                    <div class="text-danger"><%= @menu.errors[:material].first %></div>
                  <% end %>
                  <% if @menu.errors[:quantity].any? %>
                    <div class="text-danger"><%= @menu.errors[:quantity].first %></div>
                  <% end %>
                  <button type="button" class="btn btn-secondary mt-2" onclick="addMaterialQuantityForms()">材料と分量を追加</button>
                </div>
              </div>
            </div>

            <div class="form-row d-flex mt-3">
              <div class="flex-grow-1">
                <div class="mb-3">
                  <%= f.label :genre, "カレーのジャンル" %>
                  <%= f.select :genre, [["バターチキンカレー", "バターチキンカレー"], ["ドライカレー", "ドライカレー"], ["グリーンカレー", "グリーンカレー"], ["スープカレー", "スープカレー"], ["ビーフカレー", "ビーフカレー"], ["ポークカレー", "ポークカレー"], ["カツカレー", "カツカレー"], ["シーフードカレー", "シーフードカレー"], ["野菜カレー", "野菜カレー"], ["その他", "その他"]], include_blank: "選択して下さい", selected: @menu.genre %>
                  <% if @menu.errors[:genre].any? %>
                      <div class="text-danger"><%= @menu.errors[:genre].first %></div>
                  <% end %>
                </div>
              </div>
              <div class="flex-grow-1">
                <div class="mb-3">
                  <%= f.label :hot, "辛さレベル" %>
                  <%= f.select :hot, [["1:甘口", "1:甘口"], ["2:甘口〜中辛", "2:甘口〜中辛"], ["3:中辛", "3:中辛"], ["4:中辛〜辛口", "4:中辛〜辛口"], ["5:辛口", "5:辛口"]], include_blank: "選択して下さい", selected: @menu.hot %>
                  <% if @menu.errors[:hot].any? %>
                      <div class="text-danger"><%= @menu.errors[:hot].first %></div>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="mb-3 mx-3">
              作り方
              <div id="make_form_area">
                <!-- 作り方ステップのフィールド -->
                <% @menu.make.each_with_index do |make, index| %>
                  <div class="form-group">
                    <label for="make_step_<%= index + 1 %>">ステップ<%= index + 1 %></label>
                    <textarea name="menu[make][]" id="make_step_<%= index + 1 %>" class="form-control" rows="8" placeholder="作り方のステップ"><%= make %></textarea>
                    <button type="button" id="<%= index + 1 %>" onclick="deleteMakeStep(this.id)">削除</button>
                  </div>
                <% end %>
              </div>
              <% if @menu.errors[:make].any? %>
                <div class="text-danger"><%= @menu.errors[:make].first %></div>
              <% end %>
              <button type="button" class="btn btn-secondary mt-2" onclick="addMakeStep()">作り方を追加</button>
            </div>

            <div class="mb-3 mx-3">
              <%= f.label :point, "ポイント" %>
              <%= f.text_area :point, class: 'form-control', rows: 8 %>
              <% if @menu.errors[:point].any? %>
                <div class="text-danger"><%= @menu.errors[:point].first %></div>
              <% end %>
            </div>

            <%= f.submit '更新する', class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/menus/index.html.erb
<table>
  <div class="card-body">
    <tbody>
      <div class="container">
      <h1 class="text-center mb-4 mt-4">メニュー一覧</h1>
        <div class="row row-cols-1 row-cols-md-3 g-4 mb-3">
          <%= render partial: 'menu', collection: @menus %>
        </div>
      </div>
    </tbody>
  </div>
</table>

app/views/menus/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
    <h1 class="text-center mb-4 mt-4">メニュー作成</h1>
      <div class="card mt-3">
        <div class="card-body">
          <%= render 'form', menu: @menu %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/menus/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12 col-md-8">
      <div class="card mb-3">
        <div class="card-body">
          <h1>
            <%= @menu.name %>
          </h1>

          <div class="row">
            <!-- 画像を表示 -->
            <div class="col-md-6">
              <%= image_tag @menu.menu_image.url, class: 'w-100 mb-3' %>
            </div>

            <!-- 材料と分量のリストを表示 -->
            <div class="col-md-4">
              <div class="card mb-3">
                <div class="card-header">
                  材料と分量
                </div>
                <ul class="list-group list-group-flush">
                  <% @menu.material.each_with_index do |material, index| %>
                    <li class="list-group-item d-flex justify-content-between">
                      <span><%= material %></span>
                      <span><%= @menu.quantity[index] %></span>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>

          <div class="card mb-3">
            <div class="card-header">
              作り方
            </div>
            <div class="card-body">
              <% @menu.make.each_with_index do |step, index| %>
                <div class="card mb-3">
                  <div class="card-header">
                    ステップ<%= index + 1 %>
                  </div>
                  <div class="card-body">
                    <p><%= Rinku.auto_link(simple_format(step), :all, 'target="_blank"').html_safe %></p>
                  </div>
                </div>
              <% end %>
            </div>
          </div>

          <div class="card mb-3">
            <div class="card-header">
              ポイント
            </div>
            <div class="card-body">
              <%= Rinku.auto_link(simple_format(@menu.point), :all, 'target="_blank"').html_safe %>
            </div>
          </div>

          <div class="card mb-3">
            <div class="card-header">
              カレーのジャンル
            </div>
            <div class="card-body">
              <%= @menu.genre %>
            </div>
          </div>

          <div class="card mb-3">
            <div class="card-header">
              辛さレベル
            </div>
            <div class="card-body">
              <%= @menu.hot %>
            </div>
          </div>

          <% if current_user&.own?(@menu) %>
            <%= link_to '削除', menu_path(@menu.id), method: :delete, class: 'btn btn-primary ml-2', data: { confirm: '本当に削除しますか？' } %>
            <%= link_to '編集', edit_menu_path(@menu), class: 'btn btn-primary ml-2' %>
          <% end %>
          <%= link_to '戻る', menus_path, class: 'btn btn-primary ml-2' %>
        </div>
      </div>
    </div>

    <div class="col-12 col-md-4">
      <div class="card mb-3">
        <div class="card-header">
          <i class="bi bi-person"></i>
          メニュー作成者
        </div>
        <div class="card-body">
          <div class="d-flex align-items-center gap-3 mb-3">
            <%= @menu.user.name %>
          </div>
          <div class="p-3 bg-light">
            メニュー作成
            <%= @menu.user.menus.size %>
            回
          </div>
        </div>
      </div>
    </div>
  </div>
</div>