config/routes.rb
Rails.application.routes.draw do
  # Googleログイン
  post '/google_login_api/callback', to: 'google_login_api#callback'
  
  root 'menus#index'

  resources :users do
    member do
      get :favorites
    end
  end

  resources :menus do
    member do
      post :favorite, to: 'favorites#create'
    end

    resource :favorite, only: [:destroy]

    collection do
      get :back, action: :back
      post :confirm_new, action: :confirm_new
    end
    get :search, on: :collection
  end

  namespace :mypage do
    resources :tree, only: [:index]
  end

  resources :sessions, only: [:new, :create, :destroy]

  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy', as: :logout_get

  # フッターのリンクを作成
  get 'privacy', to: 'pages#privacy', as: :privacy
  get 'terms', to: 'pages#terms', as: :terms

  # お問い合わせメール
  namespace :public do
    resources :contacts, only: [:new, :create] do
      collection do
        post 'confirm'
        post 'back'
        get 'done'
      end
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :menu
  validates :user_id, uniqueness: { scope: :menu_id }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_login

  def create
    menu = Menu.find(params[:id])
    current_user.favorite(menu)
    redirect_back fallback_location: root_path, success: 'お気に入りに追加しました'
  end

  def destroy
    menu = current_user.favorite_menus.find(params[:menu_id])
    current_user.unfavorite(menu)
    redirect_back fallback_location: root_path, success: 'お気に入りを削除しました'
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<div class="menu-favorite">
  <% if current_user.present? && current_user != menu.user %>
    <% if menu.favorited_by(current_user).blank? %>
      <%= link_to "お気に入りに保存", menu_favorites_path(menu), method: :post, class: "btn btn-success btn-sm" %>
    <% else %>
      <%= link_to "保存済み", menu_favorite_path(menu, menu.favorite_by(current_user)), method: :delete, class: "btn btn-outline-success btn-sm" %>
    <% end %>
  <% else %>
    <%= link_to "お気に入りに保存", menu_favorites_path(menu), method: :post, class: "btn btn-success btn-sm", data: { confirm: 'ログインしてください' } %>
  <% end %>
</div>