config/routes.rb
Rails.application.routes.draw do
  # Googleログイン
  post '/google_login_api/callback', to: 'google_login_api#callback'
  
  root 'menus#index'

  resources :users do
    member do
      get :favorites
    end
  end

  resources :menus do
    member do
      post :favorite, to: 'favorites#create'
    end

    resource :favorite, only: [:destroy]

    collection do
      get :back, action: :back
      post :confirm_new, action: :confirm_new
    end
    get :search, on: :collection
  end

  namespace :mypage do
    resources :tree, only: [:index]
  end

  resources :sessions, only: [:new, :create, :destroy]

  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy', as: :logout_get

  # フッターのリンクを作成
  get 'privacy', to: 'pages#privacy', as: :privacy
  get 'terms', to: 'pages#terms', as: :terms

  # お問い合わせメール
  namespace :public do
    resources :contacts, only: [:new, :create] do
      collection do
        post 'confirm'
        post 'back'
        get 'done'
      end
    end
  end
end

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">



  <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
    <li class="nav-item">
      <%= link_to '利用規約', privacy_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'プライバシーポリシー', terms_path, class: 'nav-link' %>
    </li>
  </ul>


  </div>
  </div>
</nav>

app/views/shared/_header.html.erb
<%= stylesheet_link_tag 'custom_styles', media: 'all' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-custom">
  <div class="container">
    <a class="navbar-brand" href="/">CurryWeb</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if current_user.present? %>
        <span class="nav-link"><%= current_user.name %></span>
      <% else %>
        ゲスト
      <% end %>
      <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
        <%= render 'shared/search', q: @q, url: menus_path %>
        <% if current_user.present? %>
          <li class="nav-item d-flex flex-column align-items-center">
            <%= link_to user_path(current_user), class: 'nav-link small-text custom-padding-link' do %>
              <i class="bi bi-person-square"></i>
              <span>マイページ</span>
            <% end %>
          </li>
          <li class="nav-item d-flex flex-column align-items-center">
            <%= link_to favorites_user_path(current_user), class: 'nav-link small-text custom-padding-link' do %>
              <i class="bi bi-star"></i>
              <span>いいね一覧</span>
            <% end %>
          </li>
          <li class="nav-item d-flex flex-column align-items-center">
            <%= link_to menus_path, class: 'nav-link small-text custom-padding-link' do %>
              <i class="bi bi-window"></i>
              <span>投稿一覧</span>
            <% end %>
          </li>
          <li class="nav-item d-flex flex-column align-items-center">
            <%= link_to new_menu_path, class: 'nav-link small-text custom-padding-link' do %>
              <i class="bi bi-window-plus"></i>
              <span>投稿作成</span>
            <% end %>
          </li>
          <li class="nav-item d-flex flex-column align-items-center">
            <%= link_to logout_path, method: :delete, class: 'nav-link small-text custom-padding-link', data: { confirm: 'ログアウトします' } do %>
              <i class="bi bi-box-arrow-right"></i>
              <span>ログアウト</span>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item d-flex flex-column align-items-center">
            <%= link_to menus_path, class: 'nav-link small-text custom-padding-link' do %>
              <i class="bi bi-window"></i>
              <span>投稿一覧</span>
            <% end %>
          </li>
          <li class="nav-item d-flex flex-column align-items-center">
            <%= link_to new_user_path, class: 'nav-link small-text custom-padding-link' do %>
              <i class="bi bi-person-plus"></i>
              <span>登録</span>
            <% end %>
          </li>
          <li class="nav-item d-flex flex-column align-items-center">
            <%= link_to new_session_path, class: 'nav-link small-text custom-padding-link' do %>
              <i class="bi bi-box-arrow-in-left"></i>
              <span>ログイン</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_search.html.erb
<%= search_form_for @q, url: url, html: { class: 'form-inline d-flex align-items-center' } do |f| %>
  <div data-controller="autocomplete" data-autocomplete-url-value="/cats/search" role="combobox" class="d-flex align-items-center">
    <div class="form-group mr-2">
      <%= f.search_field :name_cont, data: { autocomplete_target: 'input' }, class: 'form-control', placeholder: 'メニュー名' %>
    </div>
    <div class="form-group mr-2">
      <%= f.select :hot_eq, [["辛さレベル", ""], ["1:甘口", "1:甘口"], ["2:甘口〜中辛", "2:甘口〜中辛"], ["3:中辛", "3:中辛"], ["4:中辛〜辛口", "4:中辛〜辛口"], ["5:辛口", "5:辛口"]], { include_blank: false }, class: 'form-control' %>
    </div>
    <div class="form-group mr-2">
      <%= f.select :genre_eq, [["カレージャンル", ""],["バターチキンカレー", "バターチキンカレー"], ["ドライカレー", "ドライカレー"], ["グリーンカレー", "グリーンカレー"], ["スープカレー", "スープカレー"], ["ドライカレー", "ドライカレー"], ["ビーフカレー", "ビーフカレー"], ["ポークカレー", "ポークカレー"], ["カツカレー", "カツカレー"], ["シーフードカレー", "シーフードカレー"], ["野菜カレー", "野菜カレー"], ["その他", "その他"]], { include_blank: false }, class: 'form-control' %>
    </div>
  </div>
  <%= f.submit '検索', class: 'btn btn-primary ml-2' %>
<% end %>

app/views/shared/search.html.erb
<% @menus.each do |cat| %>
  <li class="w-80 flex items-center gap-x-3.5 py-2 px-3 rounded-md text-sm text-gray-800 hover:bg-blue-200 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-blue-200 dark:hover:text-gray-300" role="option" data-autocomplete-value="<%= menu.id %>" data-autocomplete-label="<%= menu.name %>">
    <%= menu.name %>
  </li>
<% end %>